### ISSUE TITLE
External Image Support

### ISSUE THREAD

**Issue by agucova** [mettle/sendportal#130]
I noticed the default editor uses base64 to embed images in emails, which doesn't seem to work well with Gmail (at least in my case, images didn't load at all).

It would be great if the editor allowed uploading images directly, embedding them by hosting them on the platform.

**Comment by salhdev** [comment]
Hi, great and neat package !
I have made the test and got the same problem on gmail and on hotmail (outlook.com).
Yahoo was the only one that worked.

Thanks.

**Comment by JonoB** [comment]
Yes, summernote base64 encodes all images by default. It is possible to intercept one of their callbacks so that images are stored on the filesystem and then linked in the body, but that's a pretty big addition. Happy to accept a PR.

The other option is that the summernote image modal also accepts a link to an image, so you could host the image else where (github, dropbox, etc), and then just insert the link into the modal.

**Comment by faridalizade** [comment]
Hello,

I still experiencing the same issue on mobile. <img style="width: 454.203px;" src="data:image/gif;base64.....

Thanks
