### ISSUE TITLE
Add sending limits per hour/day/month for smtp servers

### ISSUE THREAD

**Issue by infabls** [mettle/sendportal#136]
Many hosting providers and SMTP servers limit the number of emails to be sent per hour, day. Can you add a setting for SMTP servers so as not to exceed the limit?

Thank you for your hard work on this product

**Comment by infabls** [comment]
Doesn't anyone care about this problem?

**Comment by b0rt** [comment]
i care, do you have a proposal for an implementation ?

**Comment by willselby** [comment]
This is difficult for us to implement as we have no way of determining how much of the quota remains available. We need to be conscious of the fact that SendPortal may not be the only service sending messages, so it's not enough for us to just define a quota and prevent sending more than that number.
We are also making adjustments to how we handle the SES quota - pushing messages back on to the queue rather than just rejecting the campaign, a change that makes this even harder to implement for SMTP.

**Comment by JonoB** [comment]
We recommend using a proper API email service instead of SMTP.

**Comment by infabls** [comment]
If, for example, I select an email address that will definitely be used only in the sendportal, can I just check how many letters are sent per hour? I've seen a similar implementation in Windows mailing list programs, but the beauty of the sendportal is that it runs on the server while I sleep.

**Comment by infabls** [comment]
> We recommend using a proper API email service instead of SMTP.

non-profit projects in developing countries cannot afford to pay dollar bills for using api services. which is a small payment for developed countries, in my country is the average monthly salary

**Comment by infabls** [comment]
I saw that you have done a certain amount of work in this direction. maybe there are some developments, a branch with this function? please tell me which way to dig
