### ISSUE TITLE
Unable to get AWS SES Working

### ISSUE THREAD

**Issue by subhajeet2107** [mettle/sendportal#23]
PHP Version: 7.2

Unable to Get AWS Ses working i have added everything in .env file, this is my .env file

AWS_ACCESS_KEY_ID=****************
AWS_SECRET_ACCESS_KEY=********************
AWS_DEFAULT_REGION=ap-south-1
AWS_BUCKET=******

I am constantly getting this error

![Screen Shot 2020-06-12 at 10 17 52 PM](https://user-images.githubusercontent.com/9478415/84526472-faef2700-acfa-11ea-8837-fa1d43a963fc.png)

I have tried adding configs directly to config/services.php

Tried changing APP_ENV to production

What am i doing wrong ?

**Comment by joshuafranks** [comment]
This is a bit of a weird one. The form shown in your screenshot is supposed to have several other fields. I've just spun up a fresh installation and when the `SES` email service is selected, this is what it looks like:

![image](https://user-images.githubusercontent.com/30936324/84550016-502e3700-ad01-11ea-8a9b-a46231f92e8e.png)

Could you bring up the `Network` tab in your browser's dev tools and take a look at what happens when you switch between the different email services? Are there any errors? When the selected email service is changed, we make an AJAX request to an endpoint which returns the correct HTML for the selected provider. If this isn't happening, then there must be something going wrong behind the scenes.

**Comment by subhajeet2107** [comment]
Thanks for the prompt reply, i have checked the console and there seems to be some mixed content issue, as our site is loaded over HTTPS, but the request is being made on HTTP, check this out:

![networktab](https://user-images.githubusercontent.com/9478415/84561863-843f4180-ad6d-11ea-953c-09b41a147868.png)

there might be some issue on our nginx setup, can you update the document to add https with nginx setup , right now it is not very clear

**Comment by subhajeet2107** [comment]
My nginx config was just fine, website was loading over https but for some reason Laravel was not detecting HTTPS, so i have put 
use Url;

UrlGenerator::forceScheme('https');

in AppServiceProvider.php

Now it is working fine, closing this issue , thanks for pointing this out !

**Comment by wzulfikar** [comment]
FWIW, I have had the same issue when trying to add Mailgun mail service. Based on suggestion from **subhajeet2107**, the issue was fixed by forcing the https scheme. For me, this is the line that I added to my AppServiceProvider (inside `boot` method):

`if($this->app->environment('production')) \URL::forceScheme('https');`

Screenshot:
![image](https://user-images.githubusercontent.com/7823011/107869539-39606580-6eca-11eb-85d0-c04b38c0c746.png)
