### ISSUE TITLE
Cron Jobs - Correctly

### ISSUE THREAD

**Issue by bartekhv** [mettle/sendportal#306]
Hello,

I installed sendportal via cpanel installer. Test messages are sent correctly. I have a problem with setting cron jobs. My path to the sendportal folder is:

/home/sites/30a/e/e50ade28e8/public_html/sender/

I am trying to run
cd /home/sites/30a/e/e50ade28e8/public_html/sender/ && php artisan schedule:run >> /dev/null 2>&1

But it doesn't work.

What is the correct path and command?
I read somewhere that it is:
cd /home/sites/30a/e/e50ade28e8/public_html/sender/artisan && php artisan schedule:run >> /dev/null 2>&1

Or
/usr/local/bin/php /home/user/laravelpath/artisan schedule:run >> /dev/null 2>&1

So i need add the path to the /php as well?

Can someone guide me? The project looks promising, unfortunately I'm stuck at this stage.

Best regards

**Comment by JonoB** [comment]
I'm not quite sure how you have this installed, because the `public` folder in github should be above the webroot, and everything else below. In your case, you have `public_html`. You need to locate the root of your project, not the public folder.

If your `public_html` maps to the `public` folder from github, then the path would be `/home/sites/30a/e/e50ade28e8/public_html/sender`
