### ISSUE TITLE
Vapor compatibility

### ISSUE THREAD

**Issue by sandervanhooft** [mettle/sendportal#32]
Hi!

Looks promising!

Can someone confirm this works with Laravel Vapor?

I know some other solutions don’t support Vapor’s queue service.

**Comment by JonoB** [comment]
None of us have tried it with Vapor - would be very interested to hear if someone gets it working!

**Comment by ninjaparade** [comment]
@JonoB @sandervanhooft I am going to try to get this stood up on vapor and see if I can't shed some light on this. I'll post an update and example you can play with if that works for you?

**Comment by JonoB** [comment]
@ninjaparade Yes please!

**Comment by ninjaparade** [comment]
Awesome, I've got a couple production apps on vapor currently so I think I'll be able to get this working quickly.

**Comment by ninjaparade** [comment]
I was able to get this done without any changes or configuration updates to the core package
there is an initial tricky step because of the CLI requirement to create the initial data which I was able to work around by connecting my local sendportal app to the RDS db instance I created.


![image](https://user-images.githubusercontent.com/228899/90545937-403a3580-e13e-11ea-91d1-a3ad15c45406.png)

**Comment by JonoB** [comment]
@ninjaparade - Amazing, thank you for doing that! I hope you don't mind, but I added a subscriber to test it out.

Sounds like there are 2 issues we'll need to sort out:

- A GUI for the initial setup (so that the setup command does not need to run in CLI mode)
- Fixing that `/home` redirect on login

Does that sound about right?

**Comment by ninjaparade** [comment]
@JonoB I don’t mind at all! I think the problem is a bit more involved because you can’t really write to the env in a vapor app. I think it could just be upfront configuration for things that need to go to the env (which would just be documentation) and then the GUI as you mentioned for the migration and last steps to configure and make your user. 

Overall it’s pretty painless I got it stood up in 10 minutes total.

**Comment by JonoB** [comment]
@sandervanhooft  and @ninjaparade - we've now included a wizard setup that can be run from the GUI. See https://sendportal.io/docs/getting-started/configuration-and-setup#setup-wizard for more info.

**Comment by ninjaparade** [comment]
@JonoB awesome nice work!

**Comment by sandervanhooft** [comment]
Nice work @JonoB !
