### ISSUE TITLE
Stuck in "sending" (1 message)

### ISSUE THREAD

**Issue by techieshark** [mettle/sendportal#33]
Hi, thanks again for this neat project. Just wondering - what could I do to debug this? I've tried to set up a sendgrid email service, but after sending a campaign it is just sort of stuck in "sending". Has been like this for 12 hours, and I'm not sure what I should look into to debug it.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1072292/84654166-0ab47880-af52-11ea-9b32-c981d82c7432.png">

I have:
* set up the SendGrid email service with API key
* set up Cron job to send as described [here](https://sendportal.io/docs/getting-started/configuration-and-setup)
* ran `php artisan sp:campaigns:dispatch` just to be sure
* looked at my php logs (didn't see anything from SendPortal)

I am:
* assuming since I put the API key in SendPortal's UI I don't need to load it in the env as shown in SendGrid [docs](https://app.sendgrid.com/guide/integrate/langs/php)

**Comment by JonoB** [comment]
Campaigns go through 4 stages: `draft` -> `queued` -> `sending` -> `sent`, and it looks like yours is stuck in the `sending` status. Running `sp:campaigns:dispatch` when a campaign is in this status will not help, because that command will only pick up campaigns with a status of `queued`.

So, there must be a reason why that single email was not sent out. Invalid email address on the subscriber, invalid API credentials for Sendgrid, or some other error related to Sendgrid.

Can you try manually updating the database by changing `status_id` back to `2` in the `campaigns` table (the `status_id` should currently be on `3`), and then run `php artisan sp:campaigns:dispatch`. You should get some output in the console, and, if there is an issue, something in your log files as well.

**Comment by techieshark** [comment]
Thanks @JonoB. 

I tried what you suggested, but just see this basic output on the console when running `php artisan sp:campaigns:dispatch`:

```
Dispatching campaigns count=1
Dispatching campaign id=12
Finished dispatching campaigns
```

I've updated my PHP-FPM config so `log_level=debug` but I'm not seeing anything relevent. FWIW, I'm running Laravel valet. 

FYI It seems that sending works for Mailgun but not Sendgrid. That is, a message is delivered. 

Test13 was sent with mailgun, test 14 + 15 with SendGrid. Note the # of sends is 0. 

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/1072292/84767983-c3dc8680-b016-11ea-884a-38237acfda17.png">

If there is an error from SendGrid, is it possible to catch that and put in the database / display onn SendPortal?

**Comment by JonoB** [comment]
So it sounds like something is failing when the message is sent to Sendgrid. When a message has been successfully accepted by your email service, then you will see something in your log file like:

```
Message has been dispatched {'message_id' => 'somerandomstring'}
```
Can you check if that's happening for Mailgun, but not for Sendgrid?

What is your `QUEUE_CONNECTION` set to the `.env` file? If it is set to `database` or `redis`, please check in the `failed_jobs` table if there are any relevant records.

Also check in Sendgrid if the emails are even hitting their logs.

**Comment by techieshark** [comment]
Hmm, no luck. Thanks though!

I'm not seeing `Message has been dispatched...` in my php-fpm.log file, even for mailgun, even with php log level set to debug. Perhaps some valet config issue.

`QUEUE_CONNECTION` was set to `sync` but I've since chaged to `database`, but after attempting a send I'm not seeing any rows in the `failed_jobs` table. 

I'm not seeing anything in SendGrid logs, though I'm a bit new to it so maybe not looking in right place.

I do see a row inserted to the `messages` table, with a hash like `767f70f7-3aab-4364-a7f0-a180dbc5dca6`, and with the expected `recipient_email` but perhaps notably the `message_id` column is `NULL`. I assume the fact that's NULL is why I see Sent: 0 on `/campaigns` page.

**Comment by PositiveZahid** [comment]
hello @JonoB 

I am also facing same kind of problem. 

What is about jobs table? does the queued message is listed on jobs table and sent with 

`php artisan sp:campaigns:dispatch`

command? 

When i run this command i see it adds rows in Jobs table. I see the output as below 

```
Dispatching campaigns count=1
Dispatching campaign id=4
Finished dispatching campaigns
```

also i see `message_id` column is `NULL`

**Comment by amenabe22** [comment]
Hitting the same issue as well not sure why this is closed should be open 

Status Queued

**Comment by ruvus11** [comment]
Got the same error with status "sending". We have connected Postmark. Normally it works well. But in the last Campagains it hungs up.  Really frustrating, because we have to send the complete Campagains again to all of the users. A better logging why it hangs or a stop and rerun wood be great.

**Comment by AdrianIul** [comment]
Hello @JonoB. I am currently facing an issue with SendPortal. I am trying to send a batch of emails via Postmark and it got stuck at one email who is apparently unsubscribed but somehow SendPortal didn't catch it via API and still tried to send the email to that user, and because of it now all the other ones are blocked from sending. Basically I need a way for the campaign that is still running to pass that user and continue with the next ones or just resume a campaign after I have deleted or manually unsubscribed the user in sendportal. Is that possible somehow?

**Comment by gusdecool** [comment]
@JonoB to confirm your suggestion at https://github.com/mettle/sendportal/issues/33#issuecomment-644572170

If we change the campaign status to queued and run dispatch, will it continue send to next recipient or repeat the recipient list from the beginning?

My concern if we send the recipient from the beginning and end up spamming our recipients.
