### ISSUE TITLE
Stuck at sending again.

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#77]
Hi,
Im trying to send out a campaign but after sending 22K emails, now its been stuck on sending status since 2-3 days now and when i click on 'View Report' for that particular campaign it throws out an error screenshot attached.

`https://imgur.com/a/F6mDtww`

Thanks.

**Comment by mpixelz** [comment]
bump

**Comment by mauricius** [comment]
Can you provide more details please? For example are you sending to all subscribers or to a segment? Which email service are you using? Which queue driver are you using?

The View Report issue is unrelated to the campaign being stuck and it's going to get fixed by [this PR](https://github.com/mettle/sendportal-core/pull/77).
