### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by nagaraj32** [mettle/sendportal#93]
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laravel/horizon is locked to version v4.3.5 and an update of this package was not requested.
    - laravel/horizon v4.3.5 requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by ingoldsby** [comment]
This is a common error when using Xampp etc. on Windows because not all the files/settings (pcntl is not available on Windows) can be used like they would be on *nix in production.

You will need to do one of the following:
1. composer install --ignore-platform-reqs
2. Add the following to your composer.json (and you can then run it without using --ignore-platform-reqs)

```
"config": {
  "platform": {
    "ext-pcntl": "7.3",
    "ext-posix": "7.3"
  }
}
```

**Comment by nagaraj32** [comment]
thanks for your response

**Comment by JonoB** [comment]
Thanks for the help @ingoldsby!
